name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.6
  - rasterio
  - numpy
  - scipy
  - pandas
  - xarray=0.11
  - matplotlib
  - dask
  - distributed
  - gcsfs
  - intake::intake
  - intake::intake-xarray
  - scikit-image
  - scikit-learn
  - dask-ml
  - bokeh
  - pyviz/label/earthsim::holoviews
  - pyviz/label/earthsim::panel
  - geoviews
  - hvplot
  - datashader
  - netcdf4
  - numcodecs
  - python-blosc
  - lz4
  - nbserverproxy
  - jupyter
  - jupyterlab=0.35
  - ipywidgets
  - ipyleaflet
  - dask-kubernetes
  - pip:
    - graphviz
    - git+https://github.com/xgcm/xgcm.git
    - git+https://github.com/zarr-developers/zarr.git